### PR TITLE
Make the site work over https

### PR DESCRIPTION
**Pull request by darthmaim**
Load all cdn assets via https, so we don't get mixed content errors when accessing the site over https.

### CODE REVIEW

**Comment by Keeky** [comment]
Fixed in 0aa8844953443b62a9d075fc506cd6f679ca1757. Thanks, completely forgot that :P

**Comment by darthmaim** [comment]
You should still use real https urls instead of protocol-relative urls, see http://www.paulirish.com/2010/the-protocol-relative-url/.

> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.
> 
> Allowing the snippet to request over HTTP opens the door for attacks like the recent Github Man-on-the-side attack. It’s always safe to request HTTPS assets even if your site is on HTTP, however the reverse is not true.

**Comment by Keeky** [comment]
Fair enough. You never stop learning :P

**Comment by darthmaim** [comment]
Fixed in 1eff13868d626f2e62fb62c822886041786d8cc0 :+1:

**Pull request closed without merging**
